// Centralized lookup lists make it straightforward to replace prototype values
// with researched datasets later without rewriting the table structure.
export const heatLoadLookupOptions = {
  directions: ["North", "Northeast", "East", "Southeast", "South", "Southwest", "West", "Northwest", "HOR"],
  wallTypes: ["Brick Wall", "Cement block Wall", "Concrete Wall"],
  roofTypes: ["Concrete Slab Roof", "Clay Roof", "Asbestos Roof"],
  glassSolarTypes: [
    "Single clear glass",
    "Single heat-absorbing glass",
    "Insulating clear glass, 6 mm air space",
    "Insulating clear glass, 13 mm air space",
    "Insulating heat-absorbing out / clear in",
  ],
  glassShadingTypes: [
    "No inside shade",
    "Venetian blinds - medium",
    "Venetian blinds - light",
    "Venetian blinds - medium closed",
    "Venetian blinds - light closed",
    "Roller shade - opaque dark",
    "Roller shade - opaque white",
    "Roller shade - translucent light",
    "Drapery A",
    "Drapery B",
    "Drapery C",
    "Drapery D",
    "Drapery E",
    "Drapery F",
    "Drapery G",
    "Drapery H",
    "Drapery I",
    "Drapery J",
  ],
  glassThicknesses: ["3", "6", "10", "13"],
  ashraeZoneTypes: ["A", "B", "C", "D"],
  internalLoadHours: [
    "1", "2", "3", "4", "5", "6", "7", "8",
    "9", "10", "11", "12", "13", "14", "15", "16",
    "17", "18", "19", "20", "21", "22", "23", "24",
  ],
  internalLoadDurations: ["2", "4", "6", "8", "10", "12", "14", "16", "18"],
  internalLightDurations: ["8", "10", "12", "14", "16"],
  wallThicknesses: ["100", "215"],
  transmissionGlassTypes: [
    "Single glass",
    "Single glass / acrylic-polycarbonate / single glass",
    "Acrylic-polycarbonate / single glass / acrylic-polycarbonate",
    "Single glass / acrylic-polycarbonate",
    "Single glass / polycarbonate",
    "6.4 mm air space",
    "12.7 mm air space",
    "6.4 mm argon space",
    "12.7 mm argon space",
  ],
  glassFrameTypes: ["Glass only (Centre of Glass)", "OperableWood/Vinyl", "Fixed Wood/Vinyl"],
  infiltrationComponents: ["Window", "Door"],
  infiltrationOccupancies: ["Residential", "Non residential"],
  infiltrationDoorComponents: ["Residential door", "Nonresidential door"],
  peopleApplications: [
    "Seated at theater",
    "Seated at theater, night",
    "Seated, very light work",
    "Moderately active office work",
    "Standing, light work; walking",
    "Walking, standing",
    "Sedentary work",
    "Light bench work",
    "Moderate dancing",
    "Walking 4.8 km/h; light machine work",
    "Bowling",
    "Heavy work",
    "Heavy machine work; lifting",
    "Athletics",
  ],
  motorPowerFactors: ["(0.04)", "(0.06)", "(0.09)", "(0.12)", "(0.19)", "(0.25)", "(0.37)", "(0.56)", "(0.75)", "(1.10)", "(1.50)", "(2.20)"],
  lampApplications: [
    "User entered incandescent/tungsten watts",
    "Fluorescent fixture, Fsa 1.20",
    "Industrial discharge fixture, Fsa 1.20",
    "Ventilated/recessed fixture, user adjusted",
  ],
  applianceApplications: [
    "Personal computer and 430 mm monitor",
    "380 mm energy-saver monitor",
    "Laser printer",
    "Desktop copier",
    "Terminal",
    "Typewriter",
    "Small copier",
    "Microwave oven",
    "Water cooler",
  ],
  ventilationApplications: [
    "Bedroom / residential",
    "Drugstore / pharmacy",
    "General application",
    "Minimum occupant outdoor air",
    "Office",
    "Hospital operating room, 6 ACH at 3 m height",
    "Manual outdoor-air flow",
  ],
} as const;
