// Centralized lookup lists make it straightforward to replace prototype values
// with researched datasets later without rewriting the table structure.
export const heatLoadLookupOptions = {
  directions: ["North", "Northeast", "East", "Southeast", "South", "Southwest", "West", "Northwest", "HOR"],
  wallTypes: ["Brick Wall", "Cement block Wall", "Concrete Wall"],
  roofTypes: ["Concrete Slab Roof", "Clay Roof", "Asbestos Roof"],
  glassSolarTypes: [
    "Single Glass Clear",
    "Single Glass Heat Absorbing",
    "Insulating Glass Clear out Clear In",
    "Insulating Glass Heat Absorbing out Clear In",
  ],
  glassShadingTypes: [
    "No shading",
    "Venetian Blinds Medium",
    "Venetian Blinds Light",
    "Opaque Dark",
    "Opaque White",
    "Translucent",
  ],
  glassThicknesses: ["3", "6", "10", "12"],
  wallThicknesses: ["100", "215"],
  transmissionGlassTypes: [
    "Single glass",
    "Single glass / acrylic-polycarbonate / single glass",
    "Acrylic-polycarbonate / single glass / acrylic-polycarbonate",
    "Single glass / acrylic-polycarbonate",
    "Single glass / polycarbonate",
    "6.4 mm air space",
    "12.7 mm air space",
    "6.4 mm argon space",
    "12.7 mm argon space",
  ],
  glassFrameTypes: ["Glass only (Centre of Glass)", "OperableWood/Vinyl", "Fixed Wood/Vinyl"],
  infiltrationComponents: ["Window", "Door"],
  infiltrationOccupancies: ["Residential", "Non residential"],
  infiltrationDoorComponents: ["Residential door", "Nonresidential door"],
  peopleApplications: [
    "Seated at Theater",
    "Seated at Theater, night",
    "Seated very light work",
    "Moderately active office work",
    "Standing, light work or walking",
    "Walking, standing",
    "Sedentary work",
    "Light bench work",
    "Moderate dancing",
    "Walking 4.8 km/h; light machine work",
    "Bowling",
    "Heavy work",
  ],
  motorPowerFactors: ["(0.04)", "(0.06)", "(0.09)", "(0.12)", "(0.19)", "(0.25)", "(0.37)", "(0.56)", "(0.75)", "(1.10)", "(1.50)", "(2.20)"],
  lampApplications: ["Office", "Residential", "Educational", "Service", "Store", "Hospital", "Production", "Farm (chicken coop)"],
  applianceApplications: [
    "Medium, desktop type",
    "2.8GHz Processor, 1GB RAM",
    "2.6GHz Processor, 2GB RAM",
    "(Model A) 3.0GHz Processor, 2GB RAM",
    "(Model B) 3.0GHz Processor, 2GB RAM",
    "2.3GHz Processor, 3GB RAM",
    "2.0GHz Processor, 2GB RAM, 430mm Screen",
    "1.8GHz Processor, 1GB RAM, 430mm Screen",
    "2.0GHz Processor, 2GB RAM, 355mm Screen",
    "2.13GHz Processor, 1GB RAM, 430mm Screen",
    "366MHz Processor, 130MB RAM, 355mm Screen",
    "900MHz Processor, 256MB RAM, 265mm Screen",
  ],
  ventilationApplications: [
    "Pharmacy",
    "Classrooms (age 9 plus)",
    "Lecture classroom",
    "Wood/metal shop",
    "Computer lab",
    "Music/theater/dance",
    "Restaurant dining rooms",
    "Cafeteria/fast food dining",
    "Bars, cocktail lounges",
    "Conference/meeting",
    "Corridors",
    "Storage room",
    "Bed room, living Room",
  ],
} as const;
